services:
  printqueue:
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - SLACK_NOTIFICATIONS_ENABLED=false

networks:
  web:
    external: false
    driver: bridge
